**Name: Aakash Thatte   
Roll number: 12041590**

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import os

fruit_class_training_folder = '/content/drive/MyDrive/Semester4/DS250/Training/Training_actual/Training/'
fruit_types = os.listdir('/content/drive/MyDrive/Semester4/DS250/Training/Training_actual/Training/')[:15]
# Initially trying on first 5 classes
print (fruit_types)  

print("Types of fruits found: ", len(fruit_types))


['Kohlrabi', 'Kumquats', 'Kiwi', 'Lemon Meyer', 'Lychee', 'Lemon', 'Limes', 'Mango Red', 'Mangostan', 'Mandarine', 'Mango', 'Melon Piel de Sapo', 'Mulberry', 'Nectarine Flat', 'Maracuja']
Types of fruits found:  15


In [ ]:
fruits = []

for item in fruit_types:
 # Get all the file names
 all_fruits = os.listdir(fruit_class_training_folder + '/' +item)
 #print(all_shoes)

 # Add them to the list
 for fruit in all_fruits:
    fruits.append((item, str(fruit_class_training_folder + '/' +item) + '/' + fruit))
    #print(fruits[:1])

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# Build a dataframe        
fruits_df = pd.DataFrame(data=fruits, columns=['fruit type', 'image'])
print(fruits_df.head())
print(fruits_df.tail())

  fruit type                                              image
0   Kohlrabi  /content/drive/MyDrive/Semester4/DS250/Trainin...
1   Kohlrabi  /content/drive/MyDrive/Semester4/DS250/Trainin...
2   Kohlrabi  /content/drive/MyDrive/Semester4/DS250/Trainin...
3   Kohlrabi  /content/drive/MyDrive/Semester4/DS250/Trainin...
4   Kohlrabi  /content/drive/MyDrive/Semester4/DS250/Trainin...
     fruit type                                              image
7290   Maracuja  /content/drive/MyDrive/Semester4/DS250/Trainin...
7291   Maracuja  /content/drive/MyDrive/Semester4/DS250/Trainin...
7292   Maracuja  /content/drive/MyDrive/Semester4/DS250/Trainin...
7293   Maracuja  /content/drive/MyDrive/Semester4/DS250/Trainin...
7294   Maracuja  /content/drive/MyDrive/Semester4/DS250/Trainin...


In [ ]:
# Let's check how many samples for each category are present
print("Total number of fruits in the dataset: ", len(fruits_df))

Total number of fruits in the dataset:  7295


In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
fruit_count = fruits_df['fruit type'].value_counts()

print("fruits in each category: ")
print(fruit_count)

fruits in each category: 
Melon Piel de Sapo    738
Lemon                 492
Mulberry              492
Kumquats              490
Lemon Meyer           490
Lychee                490
Limes                 490
Mandarine             490
Mango                 490
Maracuja              490
Nectarine Flat        480
Kohlrabi              471
Kiwi                  466
Mango Red             426
Mangostan             300
Name: fruit type, dtype: int64


In [ ]:
import cv2
path = fruit_class_training_folder


#im_size = 100
im_size = 25

images = []
labels = []

for j,i in enumerate(fruit_types):
    data_path = path + str(i) 
    filenames = [i for i in os.listdir(data_path) ]
   
    for f in filenames:
        img = cv2.imread(data_path + '/' + f)  # reading that image as array
        #print(img)  # will get the image as an array
        img = cv2.resize(img, (im_size, im_size))
        images.append(img)
        labels.append(i)
        if (j+1)%1000==0:print(j+1,"images processed")

In [ ]:
# Transform the image array to a numpy type

images = np.array(images)

images.shape

(7295, 25, 25, 3)

In [ ]:
images = images.astype('float32') / 255.0

In [ ]:
images.shape

(7295, 25, 25, 3)

In [ ]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

y=fruits_df['fruit type'].values
print(y[:15])

['Kohlrabi' 'Kohlrabi' 'Kohlrabi' 'Kohlrabi' 'Kohlrabi' 'Kohlrabi'
 'Kohlrabi' 'Kohlrabi' 'Kohlrabi' 'Kohlrabi' 'Kohlrabi' 'Kohlrabi'
 'Kohlrabi' 'Kohlrabi' 'Kohlrabi']


In [ ]:
# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)
print(len(y))

[ 1  1  1 ... 11 11 11]
7295


In [ ]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

images, y = shuffle(images, y, random_state=1)

train_x, test_x, train_y, test_y = train_test_split(images, y, test_size=0.05, random_state=415)

#inpect the shape of the training and testing.
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(6930, 25, 25, 3)
(6930,)
(365, 25, 25, 3)
(365,)


In [ ]:
# Develop a sequential model using tensorflow keras
import keras
import tensorflow as tf
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(25,25,3)),
    keras.layers.Dense(256, activation='relu'),
   
    keras.layers.Dense(5, activation=tf.nn.softmax)
])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 270000)            0         
                                                                 
 dense_2 (Dense)             (None, 256)               69120256  
                                                                 
 dense_3 (Dense)             (None, 5)                 1285      
                                                                 
Total params: 69,121,541
Trainable params: 69,121,541
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Compute the model parameters

model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
# Train the model  with 5 epochs 

model.fit(train_x,train_y, epochs=5)

Epoch 1/5
72/72 [==============================] - 26s 361ms/step - loss: 3.8404 - accuracy: 0.2756
Epoch 2/5
72/72 [==============================] - 26s 361ms/step - loss: 1.4866 - accuracy: 0.3395
Epoch 3/5
72/72 [==============================] - 26s 365ms/step - loss: 1.4208 - accuracy: 0.3806
Epoch 4/5
72/72 [==============================] - 35s 493ms/step - loss: 1.3743 - accuracy: 0.3902
Epoch 5/5
72/72 [==============================] - 26s 361ms/step - loss: 1.3366 - accuracy: 0.4108


In [ ]:
y_pred = model.predict_classes(test_x)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [ ]:
# Tweaking the parameters
model2 = keras.Sequential([
    keras.layers.Flatten(input_shape=(25,25,3)),
    keras.layers.Dense(300, activation='relu'),
    keras.layers.Dense(200, activation='relu'),
    keras.layers.Dense(15, activation='relu')
])

model2.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model2.fit(train_x,train_y, epochs=10)

Epoch 1/10
217/217 [==============================] - 2s 6ms/step - loss: 13.5858 - accuracy: 0.0641
Epoch 2/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 3/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 4/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 5/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 6/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 7/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 8/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 9/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accuracy: 0.0644
Epoch 10/10
217/217 [==============================] - 1s 6ms/step - loss: 13.6140 - accura

In [ ]:
from keras.preprocessing.image import load_img

import numpy as np

image = load_img('===', target_size=(300, 300))   # predicting correct 
image

In [ ]:
# convert the image pixels to a numpy array
image = np.array(image)
image.shape

# reshape data for the model
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))



In [ ]:
yhat = model.predict(image)
yhat

array([[0.31677377, 0.3919051 , 0.29132116]], dtype=float32)

In [ ]:
# Just trying, if fails, run all cells from above
import cv2
from skimage.feature import hog
from skimage.transform import resize
from skimage.io import imread, imshow
path = fruit_class_training_folder


#im_size = 100
#im_size = 300

images = []
labels = []

for j,i in enumerate(fruit_types):
    data_path = path + str(i) 
    filenames = [i for i in os.listdir(data_path) ]
   
    for f in filenames:
        img = imread(data_path + '/' + f)  # reading that image as array
        #print(img)  # will get the image as an array
        #img = cv2.resize(img, (im_size, im_size))
        hog_ = hog(resize(img, (128,64)) , orientations=8, pixels_per_cell=(16, 16), cells_per_block=(1, 1), visualize=False, multichannel=True)
        images.append(hog_)
        labels.append(i)
        if (j+1)%1000==0:print(j+1,"images processed")

In [ ]:
# Transform the image array to a numpy type

images = np.array(images)

images.shape

(7295, 256)

In [ ]:
images = images.astype('float32')

In [ ]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split


images, y = shuffle(images, y, random_state=1)

train_x, test_x, train_y, test_y = train_test_split(images, y, test_size=0.05, random_state=415)

#inpect the shape of the training and testing.
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(6930, 256)
(6930,)
(365, 256)
(365,)


In [ ]:
import keras
import tensorflow as tf
model_new = keras.Sequential([
    keras.layers.Flatten(input_shape=(256,)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(15, activation='relu')
])

model_new.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model_new.fit(train_x,train_y, epochs=10)

Epoch 1/10
217/217 [==============================] - 1s 2ms/step - loss: 6.3228 - accuracy: 0.0928
Epoch 2/10
217/217 [==============================] - 1s 2ms/step - loss: 5.7496 - accuracy: 0.1014
Epoch 3/10
217/217 [==============================] - 0s 2ms/step - loss: 5.4996 - accuracy: 0.1014
Epoch 4/10
217/217 [==============================] - 0s 2ms/step - loss: 5.4787 - accuracy: 0.1051
Epoch 5/10
217/217 [==============================] - 0s 2ms/step - loss: 5.7078 - accuracy: 0.1113
Epoch 6/10
217/217 [==============================] - 0s 2ms/step - loss: 5.3093 - accuracy: 0.1456
Epoch 7/10
217/217 [==============================] - 0s 2ms/step - loss: 5.2548 - accuracy: 0.1514
Epoch 8/10
217/217 [==============================] - 0s 2ms/step - loss: 5.5676 - accuracy: 0.1709
Epoch 9/10
217/217 [==============================] - 0s 2ms/step - loss: 2.6052 - accuracy: 0.1169
Epoch 10/10
217/217 [==============================] - 0s 2ms/step - loss: 2.7080 - accuracy: 0.0644